### ISSUE TITLE
index.md의 마크다운 이슈

### ISSUE THREAD

**Issue by neont21** [phg98/korean-repo#5]
맨 마지막 문단이 시작되기 전에 '---'가 아닌 '```'가 들어가 맨 마지막 문단이 코드블록으로 취급되고 있습니다.
마크다운 링크가 포함되어 있는 것으로 보아 의도적이지 않은 상황으로 보이는데
코드블록으로 취급됨으로써 마크다운 링크가 작동하지 않고 있습니다.
사소한 것이지만 수정이 필요할 것으로 보입니다.

**Comment by phg98** [comment]
아앗, 그렇군요!
매의 눈을 가지셨네요! ㅎㅎ
수정해서 PR보내주시면 감사하겠습니다. ㅎㅎ
